version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '1323:1323'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: arm64v8/mysql:oracle
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - data_3:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'test_db'

volumes:
  data_3: